version: '3.8'

services:
    server:
        depends_on:
              - db
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/var/www/html/
        ports:
            - 8000:80
            
    db:
        container_name: db
        build:
            context: ./db
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./db/init.sql:/var/www/sql/init.sql
        command: --init-file /var/www/sql/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: appDB
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "9906:3306"